In [165]:
import numpy  as np
import matplotlib.pyplot as plt


#at Tx
k=10   #number of nodes
N=7    #number of slots
channel_gain=1.2

source=np.random.randn(k)   #node values
source


array([-0.17706497,  0.42549002,  0.36484562, -1.37039157, -0.61696471,
       -0.29429433, -0.71021364,  2.07415919,  0.75830753,  1.4611657 ])

In [166]:
channel_coeff=np.random.rayleigh(1,k)
values_tobe_transmitted=source[channel_coeff>channel_gain]
non_transmitted=source[channel_coeff<=channel_gain]

#transmitted=values_tobe_transmitted*channel_coeff[channel_coeff>channel_gain]
transmitted=np.sum(values_tobe_transmitted*channel_coeff[channel_coeff>channel_gain])+np.random.randn()
recieved=transmitted+np.random.randn()

print("node values where channel coeffs are greater than channel  threshold: \n",values_tobe_transmitted,len(values_tobe_transmitted))
print("node vaues less than channel threshold\n",non_transmitted,len(non_transmitted))
print("TRANSMITTED::",transmitted)
print("RECIEVED::",recieved)

node values where channel coeffs are greater than channel  threshold: 
 [-0.17706497  0.42549002 -0.61696471 -0.29429433 -0.71021364  0.75830753
  1.4611657 ] 7
node vaues less than channel threshold
 [ 0.36484562 -1.37039157  2.07415919] 3
TRANSMITTED:: 0.6471691078023203
RECIEVED:: 1.6917052895978728


In [167]:
for i in range(1,N+1):
    if(len(non_transmitted)):
        print(i+1,"th slot")
        source=non_transmitted
        channel_coeff=np.random.rayleigh(1,len(source))
        values_tobe_transmitted=source[channel_coeff>channel_gain]
        non_transmitted=source[channel_coeff<=channel_gain]

        transmitted=np.sum(values_tobe_transmitted*channel_coeff[channel_coeff>channel_gain])
        recieved=transmitted+np.random.randn()

        print("node values where channel coeffs are greater than channel  threshold: \n",values_tobe_transmitted,len(values_tobe_transmitted))
        print("node vaues less than channel threshold\n",non_transmitted,len(non_transmitted))
        
        print("TRANSMITTED::",transmitted)
        print("RECIEVED::",recieved)
        print("\n")
        #transmitted=np.sum(values_tobe_transmitted*channel_coeff([channel_coeff>channel_gain]))+np.random.normal(0,1)


2 th slot
node values where channel coeffs are greater than channel  threshold: 
 [ 0.36484562 -1.37039157  2.07415919] 3
node vaues less than channel threshold
 [] 0
TRANSMITTED:: 0.40232839312897495
RECIEVED:: -0.8820916438653712




In [168]:
#pre_func=1/channel_coeff
noise=np.random.normal(0,1)


values_greater_than_channel_coeff=source[channel_coeff>channel_gain]
transmitted=np.sum(source*channel_coeff)
non_trasmitted_values=source[channel_coeff<channel_gain]
print(len(source[channel_coeff>channel_gain]))

for i in range(1,N+1):
    if len(source):
        channel_coeff=np.random.rayleigh(1,len(non_trasmitted_values+1))
        source=non_trasmitted_values
        trasmitted=np.sum(source[channel_coeff>channel_gain])
        non_trasmitted_values=source[channel_coeff<channel_gain]
        print(len(source[channel_coeff>channel_gain]))
        recieved=transmitted+noise
        error=abs(recieved-transmitted)

print

3
0


<function print>