In [34]:
import numpy as np
import  matplotlib.pyplot as plt
from scipy import special as sp


In [58]:
bits=np.array([[1,1,0,1,0,0,1,1],[0,0,0,1,1,0,1,1]])
print(bits)
import numpy as np

# Iterate over each row
for row in bits:
    # Iterate through pairs of bits in the current row
    for i in range(0, len(row), 2):
        pair = row[i:i+2]
        print(f"Bits from columns {i} to {i+1} in row: {pair}")


[[1 1 0 1 0 0 1 1]
 [0 0 0 1 1 0 1 1]]
Bits from columns 0 to 1 in row: [1 1]
Bits from columns 2 to 3 in row: [0 1]
Bits from columns 4 to 5 in row: [0 0]
Bits from columns 6 to 7 in row: [1 1]
Bits from columns 0 to 1 in row: [0 0]
Bits from columns 2 to 3 in row: [0 1]
Bits from columns 4 to 5 in row: [1 0]
Bits from columns 6 to 7 in row: [1 1]


In [52]:
bits=np.array([[1,1,0,1,0,0,1,1],[0,0,0,1,1,0,1,1]])
print(bits)
#print(a)
mapping = {
    (0,0):1+1j,
    (0,1):-1+1j,
    (1,0):1-1j,
    (1,1):-1-1j
}
#modulation
symbols=np.array([])
for i in range(0,len(bits),2):
    bit_pair=(bits[[i]],bits[[i+1]])
    symbols=np.append(symbols,mapping[bit_pair])
#print("mod",modulated_bits)
symbols


[[1 1 0 1 0 0 1 1]
 [0 0 0 1 1 0 1 1]]


TypeError: unhashable type: 'numpy.ndarray'

In [36]:
def qpsk_demod(received_signal):
    symbols = {
        1 + 1j: (0, 0),
        -1 + 1j: (0, 1),
        1 - 1j: (1, 0),
        -1 - 1j: (1, 1)
    }

    #demodulation
    demodulated_bits=np.array([])
    for i in received_signal:
        closest_symbol = min(symbols.keys(), key=lambda s: np.abs(i - s))
        demodulated_bits=np.append(demodulated_bits,(symbols[closest_symbol]))
    #    print(np.array(demodulated_bits))

    received_signal1=np.array([int(i)  for i in demodulated_bits])
    #converting into int just for appearance
    return received_signal1


In [39]:
def simulate(no_of_users,snr_db):
    no_of_bits=16
    msg_bits=np.random.randint(0,2,(no_of_users,no_of_bits))
    msg_bits


    symbols=qpsk_mod(msg_bits)
    print(symbols)


    signal_sum=np.sum(symbols,axis=0)



    snr_lin=10**(snr_db/10)
    noise_power=1/snr_lin  


    ber=np.array([])
    for noispower in noise_power:
        noise=np.sqrt(noispower)*np.random.randn(len(signal_sum))
        received_symbols=signal_sum+noise
        
        if no_of_users == 2:
            recover_sym = np.where(received_symbols < -1, -2, np.where(received_symbols > 1, 2, 0))
        else:
            recover_sym = qpsk_demod(received_symbols)
            #recover_bits=np.where(recover_sym<0,0,1)
        
        ser=np.mean(signal_sum!=recover_sym)
        ber.append(ser/2 if no_of_users==1 else ser/4)
    return ber


In [40]:
no_of_users=1
snr_db=np.arange(0,12,1)

ber1=simulate(no_of_users,snr_db)
plt.semilogy(snr_db,ber1)

#no_of_users=2
#ber2=simulate(no_of_users,snr_db)
#plt.semilogy(snr_db,ber2)

plt.grid(True, which='both')
plt.xlabel("SNR")
plt.ylabel("BER")
plt.legend(['qpsk'])
plt.show()

IndexError: index 1 is out of bounds for axis 0 with size 1